#!/usr/bin/env python3
"""Deterministic synthetic fixture generator for the v18 benchmark.

Emits a 50k+ LOC synthetic repository (Python/Rust/TypeScript) with novel
names under docs/benchmarks/v18/fixture/, plus a manifest.json carrying a
_source provenance field. Output depends only on --seed and --output, so
regenerating with the same seed reproduces the committed fixture byte for
byte (CI verifies by hash, not full diff).
"""

from __future__ import annotations

import argparse
import json
import random
from pathlib import Path

DEFAULT_SEED = 1604
DEFAULT_OUTPUT = Path("docs/benchmarks/v18/fixture")
TARGET_LOC = 55_000
# Per-function line counts per language (signature + body + blanks).
LOC_PER_FUNC = {"py": 9, "rs": 10, "ts": 8}

SYLLABLES_A = [
    "zeph", "quor", "velm", "tarn", "glom", "firn", "mox", "hlud",
    "cren", "sylv", "ondr", "pax", "vyr", "thon", "bram", "lisk",
]
SYLLABLES_B = [
    "ir", "ax", "eth", "urn", "ole", "ic", "ant", "esh",
    "ith", "or", "yne", "aul", "ist", "ov", "en", "ur",
]
CONCEPTS = [
    "ledger", "throttle", "index", "cursor", "window", "batch",
    "frame", "queue", "cache", "router", "mapper", "token",
]
TAG_FMT = "V18ANS-{i:04d}"


def _name(rng: random.Random) -> str:
    return rng.choice(SYLLABLES_A) + rng.choice(SYLLABLES_B)


def _func_name(rng: random.Random, i: int) -> str:
    return f"{_name(rng)}_{CONCEPTS[i % len(CONCEPTS)]}_{i:04d}"


def _py_func(rng: random.Random, i: int, answer: str) -> str:
    fn = _func_name(rng, i)
    return (
        f"def {fn}(payload):\n"
        f"    \"\"\"Fold payload for stage {i}.\"\"\"\n"
        f"    marker = \"{answer}\"\n"
        f"    if not payload:\n"
        f"        return marker\n"
        f"    acc = []\n"
        f"    for item in payload:\n"
        f"        acc.append(str(item) + marker)\n"
        f"    return \"|\".join(acc)\n"
    )


def _rs_func(rng: random.Random, i: int, answer: str) -> str:
    fn = _func_name(rng, i)
    return (
        f"fn {fn}(payload: &[String]) -> String {{\n"
        f"    let marker = \"{answer}\";\n"
        f"    if payload.is_empty() {{\n"
        f"        return marker.to_string();\n"
        f"    }}\n"
        f"    payload.iter()\n"
        f"        .map(|item| format!(\"{{item}}{{marker}}\"))\n"
        f"        .collect::<Vec<_>>()\n"
        f"        .join(\"|\")\n"
        f"}}\n"
    )


def _ts_func(rng: random.Random, i: int, answer: str) -> str:
    fn = _func_name(rng, i)
    return (
        f"export function {fn}(payload: string[]): string {{\n"
        f"  const marker = \"{answer}\";\n"
        f"  if (payload.length === 0) {{\n"
        f"    return marker;\n"
        f"  }}\n"
        f"  return payload.map((item) => item + marker).join(\"|\");\n"
        f"}}\n"
    )


EMITTERS = {"py": _py_func, "rs": _rs_func, "ts": _ts_func}


def generate(seed: int, out_root: Path) -> dict:
    """Generate the fixture tree; returns the manifest dict."""
    rng = random.Random(seed)
    if out_root.exists():
        for p in sorted(out_root.rglob("*"), reverse=True):
            p.unlink() if p.is_file() else p.rmdir()
    packages = ["", "core", "ingest", "render", "storage", "wire"]
    written = {"py": 0, "rs": 0, "ts": 0}
    answers: list[dict] = []
    total_loc = 0
    func_i = 0
    file_i = 0
    while total_loc < TARGET_LOC:
        lang = ("py", "rs", "ts")[file_i % 3]
        pkg = packages[file_i % len(packages)]
        stem = f"{_name(rng)}_{_name(rng)}_{file_i:04d}"
        rel = (Path(pkg) / f"{stem}.{lang}") if pkg else Path(f"{stem}.{lang}")
        abs_path = out_root / rel
        abs_path.parent.mkdir(parents=True, exist_ok=True)
        n_funcs = rng.randint(4, 8)
        parts = []
        for _ in range(n_funcs):
            tag = TAG_FMT.format(i=func_i)
            answer = f"{tag}:{_name(rng)}-{func_i:04d}"
            parts.append(EMITTERS[lang](rng, func_i, answer))
            total_loc += LOC_PER_FUNC[lang]
            answers.append({
                "id": f"q-{func_i:04d}",
                "tag": tag,
                "answer": answer,
                "path": rel.as_posix(),
            })
            func_i += 1
        abs_path.write_text("".join(parts), encoding="utf-8")
        written[lang] += 1
        file_i += 1
    manifest = {
        "_source": (
            "generated by scripts/bench_v18/generate_fixture.py "
            f"--seed {seed}; deterministic, do not hand-edit"
        ),
        "seed": seed,
        "loc_estimate": total_loc,
        "files": written,
        "answers": answers,
    }
    (out_root / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--seed", type=int, default=DEFAULT_SEED)
    ap.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
        help="fixture root (repo-relative or absolute)",
    )
    args = ap.parse_args()
    manifest = generate(args.seed, args.output)
    print(
        f"wrote fixture: {args.output} "
        f"loc~{manifest['loc_estimate']} files={manifest['files']}"
    )


if __name__ == "__main__":
    main()
