"""Fixture and oracle tests: determinism, LOC floor, oracle spot-checks."""

import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from bench_v18 import generate_fixture, oracle

SEED = 1604


def _fixture(tmp_path):
    root = tmp_path / "fixture"
    generate_fixture.generate(SEED, root)
    return root


def _tree_hash(root: Path) -> str:
    h = hashlib.sha256()
    for p in sorted(root.rglob("*")):
        if p.is_file():
            h.update(p.relative_to(root).as_posix().encode())
            h.update(p.read_bytes())
    return h.hexdigest()


def test_seeded_generation_is_deterministic(tmp_path):
    a = tmp_path / "a"
    b = tmp_path / "b"
    generate_fixture.generate(SEED, a)
    generate_fixture.generate(SEED, b)
    assert _tree_hash(a) == _tree_hash(b)


def test_loc_floor_and_multi_language_with_provenance(tmp_path):
    fx = _fixture(tmp_path)
    manifest = json.loads((fx / "manifest.json").read_text(encoding="utf-8"))
    assert manifest["_source"].startswith("generated by scripts/bench_v18/")
    assert manifest["loc_estimate"] >= 50_000
    actual_loc = 0
    for p in fx.rglob("*"):
        if p.suffix in (".py", ".rs", ".ts"):
            actual_loc += len(p.read_text(encoding="utf-8").splitlines())
    assert actual_loc >= 50_000
    assert set(manifest["files"].values()) and len(manifest["files"]) == 3
    assert all(n > 0 for n in manifest["files"].values())


def test_oracle_spot_checks_via_search(tmp_path):
    fx = _fixture(tmp_path)
    entries = oracle.build_oracle(fx)
    assert len(entries) == oracle.N_QUESTIONS
    for entry in entries[:5]:
        rel, lineno = entry["anchor"].rsplit(":", 1)
        line = (fx / rel).read_text(encoding="utf-8").splitlines()[
            int(lineno) - 1
        ]
        assert entry["expected"] in line
        assert entry["id"].startswith("q-")
